a = 9
x = 1
print(a,"*",x," =",a*x)
x = x + 1
print(a,"*",x," =",a*x)
x = x + 1
print(a,"*",x," =",a*x)
x = x + 1
print(a,"*",x," =",a*x)
x = x + 1
print(a,"*",x," =",a*x)
x = x + 1
print(a,"*",x," =",a*x)
x = x + 1
print(a,"*",x," =",a*x)
x = x + 1
print(a,"*",x," =",a*x)
x = x + 1
print(a,"*",x," =",a*x)
x = x + 1
print(a,"*",x," =",a*x)
x = x + 1
